
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// .env.local (pulled from Vercel via `vercel env pull`) takes precedence over .env,
// matching Next.js's own env file precedence.
config({ path: [".env", ".env.local"], override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
